import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  page: {
    minHeight: 720,
    padding: 24,
    gap: 18,
    backgroundColor: "#111827",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 6,
  },
  realmLabel: {
    color: "#8fd3c7",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  playerText: {
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "800",
  },
  scene: {
    minHeight: 620,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#273549",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    padding: 34,
  },
  caveStage: {
    width: 500,
    height: 460,
    alignItems: "center",
    justifyContent: "flex-end",
  },
  caveMouth: {
    width: 410,
    height: 350,
    borderTopLeftRadius: 210,
    borderTopRightRadius: 210,
    backgroundColor: "#1f2937",
    borderWidth: 12,
    borderColor: "#4b5563",
    alignItems: "center",
    justifyContent: "center",
  },
  bossSilhouette: {
    width: 170,
    height: 190,
    borderTopLeftRadius: 84,
    borderTopRightRadius: 84,
    borderBottomLeftRadius: 26,
    borderBottomRightRadius: 26,
    backgroundColor: "#7c2d12",
    borderWidth: 6,
    borderColor: "#f7c35f",
    alignItems: "center",
    justifyContent: "center",
  },
  bossInitial: {
    color: "#fff7ed",
    fontSize: 74,
    fontWeight: "900",
  },
  ground: {
    width: 480,
    height: 56,
    marginTop: -20,
    borderRadius: 8,
    backgroundColor: "#3f2f25",
  },
  panel: {
    width: 500,
    padding: 24,
    borderRadius: 8,
    backgroundColor: "rgba(15, 23, 42, 0.92)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    gap: 14,
  },
  kicker: {
    color: "#f7c35f",
    fontSize: 13,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  title: {
    color: "#f8fafc",
    fontSize: 36,
    fontWeight: "900",
  },
  subtitle: {
    color: "#cbd5e1",
    fontSize: 15,
    lineHeight: 22,
  },
  statGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  statCard: {
    width: "47%",
    minHeight: 74,
    padding: 12,
    borderRadius: 6,
    backgroundColor: "#1f2937",
  },
  statLabel: {
    color: "#94a3b8",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  statValue: {
    color: "#f8fafc",
    fontSize: 19,
    fontWeight: "900",
    marginTop: 8,
  },
  resultPanel: {
    gap: 6,
    padding: 14,
    borderRadius: 6,
    backgroundColor: "#0f766e",
  },
  resultTitle: {
    color: "#f0fdfa",
    fontSize: 17,
    fontWeight: "900",
  },
  resultLine: {
    color: "#ccfbf1",
    fontSize: 14,
    fontWeight: "800",
  },
  duplicateText: {
    color: "#fde68a",
    fontSize: 13,
    fontWeight: "900",
  },
  actions: {
    minHeight: 54,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  primaryButton: {
    minHeight: 52,
    minWidth: 160,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
    backgroundColor: "#f7c35f",
    paddingHorizontal: 16,
  },
  primaryButtonText: {
    color: "#22160a",
    fontSize: 15,
    fontWeight: "900",
  },
  smallButton: {
    borderRadius: 6,
    backgroundColor: "#f8fafc",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  smallButtonDark: {
    backgroundColor: "#374151",
  },
  smallButtonText: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "900",
  },
  smallButtonTextDark: {
    color: "#f8fafc",
  },
  disabled: {
    opacity: 0.55,
  },
  errorText: {
    color: "#fecaca",
    fontSize: 14,
    lineHeight: 20,
  },
});
