import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  page: {
    minHeight: 720,
    padding: 24,
    gap: 18,
    backgroundColor: "#172033",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 6,
  },
  realmLabel: {
    color: "#8fd3c7",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  playerText: {
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "800",
  },
  headerActions: {
    flexDirection: "row",
    gap: 10,
  },
  scene: {
    minHeight: 620,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#4f6f57",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    padding: 34,
  },
  market: {
    width: 440,
    height: 430,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  merchantSlot: {
    marginBottom: -26,
    zIndex: 0,
  },
  statValueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
  },
  statValueInline: {
    marginTop: 0,
  },
  awning: {
    width: 360,
    height: 72,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    overflow: "hidden",
    flexDirection: "row",
    borderWidth: 4,
    borderColor: "#f8fafc",
  },
  awningStripe: {
    flex: 1,
    backgroundColor: "#b91c1c",
  },
  awningStripeAlt: {
    backgroundColor: "#f7c35f",
  },
  counter: {
    width: 390,
    height: 170,
    backgroundColor: "#7c4a2d",
    borderWidth: 8,
    borderColor: "#3b281f",
    alignItems: "center",
    justifyContent: "center",
  },
  counterText: {
    color: "#fff7ed",
    fontSize: 26,
    fontWeight: "900",
  },
  crates: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 14,
    marginTop: 18,
  },
  crate: {
    width: 78,
    height: 62,
    backgroundColor: "#925f35",
    borderWidth: 5,
    borderColor: "#5f3a22",
  },
  crateTall: {
    width: 86,
    height: 92,
    backgroundColor: "#a96d3a",
    borderWidth: 5,
    borderColor: "#5f3a22",
  },
  dashboard: {
    width: 500,
    padding: 24,
    borderRadius: 8,
    backgroundColor: "rgba(15, 23, 42, 0.9)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    gap: 14,
  },
  title: {
    color: "#f8fafc",
    fontSize: 34,
    fontWeight: "900",
  },
  subtitle: {
    color: "#cbd5e1",
    fontSize: 15,
    lineHeight: 22,
  },
  statGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  statCard: {
    width: "47%",
    minHeight: 86,
    padding: 12,
    borderRadius: 6,
    backgroundColor: "#1f2937",
  },
  statLabel: {
    color: "#94a3b8",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  statValue: {
    color: "#f8fafc",
    fontSize: 20,
    fontWeight: "900",
    marginTop: 8,
  },
  arenaStrip: {
    padding: 14,
    borderRadius: 6,
    backgroundColor: "#0f766e",
  },
  arenaStripLabel: {
    color: "#ccfbf1",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  arenaStripValue: {
    color: "#f0fdfa",
    fontSize: 19,
    fontWeight: "900",
    marginTop: 4,
  },
  contentPanel: {
    gap: 8,
    padding: 12,
    borderRadius: 6,
    backgroundColor: "#111827",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  sectionTitle: {
    color: "#f8fafc",
    fontSize: 16,
    fontWeight: "900",
  },
  sectionHint: {
    color: "#94a3b8",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  contentRow: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    padding: 10,
    borderRadius: 6,
    backgroundColor: "#1f2937",
  },
  contentRowEnabled: {
    borderWidth: 1,
    borderColor: "rgba(247,195,95,0.42)",
  },
  contentRowDisabled: {
    opacity: 0.55,
  },
  contentRowMain: {
    flex: 1,
    minWidth: 0,
  },
  contentRowTitle: {
    color: "#f8fafc",
    fontSize: 14,
    fontWeight: "900",
  },
  contentRowSubtitle: {
    color: "#cbd5e1",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 3,
  },
  badgeGroup: {
    flexDirection: "row",
    gap: 6,
  },
  badge: {
    minWidth: 46,
    overflow: "hidden",
    borderRadius: 5,
    backgroundColor: "#374151",
    color: "#e5e7eb",
    fontSize: 12,
    fontWeight: "900",
    paddingHorizontal: 8,
    paddingVertical: 5,
    textAlign: "center",
  },
  priceText: {
    color: "#f7c35f",
    fontSize: 13,
    fontWeight: "900",
  },
  inlineButton: {
    minWidth: 86,
    minHeight: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
    backgroundColor: "#f7c35f",
    paddingHorizontal: 10,
  },
  inlineButtonText: {
    color: "#22160a",
    fontSize: 12,
    fontWeight: "900",
  },
  emptyText: {
    color: "#cbd5e1",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 19,
  },
  actions: {
    flexDirection: "row",
    gap: 10,
  },
  primaryButton: {
    minHeight: 52,
    minWidth: 150,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
    backgroundColor: "#f7c35f",
    paddingHorizontal: 16,
  },
  primaryButtonText: {
    color: "#22160a",
    fontSize: 15,
    fontWeight: "900",
  },
  disabledAction: {
    minHeight: 52,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
    backgroundColor: "#374151",
    paddingHorizontal: 14,
  },
  disabledActionText: {
    color: "#cbd5e1",
    fontSize: 13,
    fontWeight: "800",
  },
  smallButton: {
    borderRadius: 6,
    backgroundColor: "#f8fafc",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  smallButtonDark: {
    backgroundColor: "#374151",
  },
  smallButtonText: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "900",
  },
  smallButtonTextDark: {
    color: "#f8fafc",
  },
  disabled: {
    opacity: 0.55,
  },
  errorText: {
    color: "#fecaca",
    fontSize: 14,
    lineHeight: 20,
  },
  loadingText: {
    color: "#bfdbfe",
    fontSize: 14,
    fontWeight: "800",
  },
});
