import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  page: {
    minHeight: 720,
    padding: 24,
    gap: 18,
    backgroundColor: "#101827",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 6,
  },
  realmLabel: {
    color: "#f7c35f",
    fontSize: 12,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  playerText: {
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "800",
  },
  headerActions: {
    flexDirection: "row",
    gap: 10,
  },
  scene: {
    minHeight: 620,
    borderRadius: 8,
    overflow: "hidden",
    backgroundColor: "#20314f",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-around",
    padding: 34,
  },
  colosseumWall: {
    position: "absolute",
    left: 28,
    right: 28,
    bottom: 42,
    height: 300,
    borderTopLeftRadius: 190,
    borderTopRightRadius: 190,
    backgroundColor: "#c99555",
    borderWidth: 8,
    borderColor: "#efd18a",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingHorizontal: 32,
  },
  wallArch: {
    width: 58,
    height: 126,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: "#5c3f2d",
    marginTop: 72,
  },
  pillarWrap: {
    width: 170,
    alignItems: "center",
    zIndex: 2,
  },
  pillarCap: {
    width: 158,
    height: 28,
    borderRadius: 6,
    backgroundColor: "#f0d08b",
  },
  pillar: {
    width: 104,
    height: 370,
    overflow: "hidden",
    backgroundColor: "#e6e0cf",
    borderLeftWidth: 10,
    borderRightWidth: 10,
    borderColor: "#b9a77e",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  pillarFill: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#f59e0b",
  },
  levelBadge: {
    width: 78,
    height: 78,
    borderRadius: 39,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#111827",
    borderWidth: 4,
    borderColor: "#f8fafc",
    marginBottom: 140,
  },
  levelBadgeText: {
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "900",
  },
  pillarBase: {
    width: 188,
    height: 34,
    borderRadius: 6,
    backgroundColor: "#b97835",
  },
  infoPanel: {
    width: 360,
    padding: 24,
    borderRadius: 8,
    backgroundColor: "rgba(15, 23, 42, 0.88)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    gap: 12,
    zIndex: 2,
  },
  title: {
    color: "#f8fafc",
    fontSize: 34,
    fontWeight: "900",
  },
  progressText: {
    color: "#f7c35f",
    fontSize: 24,
    fontWeight: "900",
  },
  nextText: {
    color: "#cbd5e1",
    fontSize: 15,
    lineHeight: 21,
  },
  healthRow: {
    flexDirection: "row",
    gap: 8,
  },
  healthPill: {
    flex: 1,
    padding: 10,
    borderRadius: 6,
    backgroundColor: "#1f2937",
  },
  healthLabel: {
    color: "#94a3b8",
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  healthValue: {
    color: "#f8fafc",
    fontSize: 14,
    fontWeight: "800",
  },
  errorText: {
    color: "#fecaca",
    fontSize: 14,
    lineHeight: 20,
  },
  gateButton: {
    minHeight: 54,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
    backgroundColor: "#f7c35f",
    marginTop: 8,
  },
  gateText: {
    color: "#22160a",
    fontSize: 16,
    fontWeight: "900",
  },
  smallButton: {
    borderRadius: 6,
    backgroundColor: "#f8fafc",
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  smallButtonDark: {
    backgroundColor: "#374151",
  },
  smallButtonText: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "900",
  },
  smallButtonTextDark: {
    color: "#f8fafc",
  },
  pressed: {
    opacity: 0.85,
    transform: [{ translateY: 1 }],
  },
  levelMarker: {
    position: "absolute",
    left: 0,
    right: 0,
    alignItems: "center",
  },
  markerTick: {
    height: 2,
    alignSelf: "stretch",
    backgroundColor: "#b9a77e",
    opacity: 0.7,
  },
  markerTickReached: {
    backgroundColor: "#f7c35f",
    opacity: 1,
  },
  markerChip: {
    position: "absolute",
    top: -8,
    backgroundColor: "#111827",
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderWidth: 1,
    borderColor: "#b9a77e",
  },
  markerChipReached: {
    borderColor: "#f7c35f",
  },
  markerChipText: {
    color: "#cbd5e1",
    fontSize: 9,
    fontWeight: "900",
  },
  markerChipTextReached: {
    color: "#f7c35f",
  },
  progressRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  emptyText: {
    color: "#cbd5e1",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "700",
  },
  warningText: {
    color: "#fcd34d",
    fontSize: 13,
    lineHeight: 19,
  },
  gateOverlay: {
    position: "absolute",
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(8, 12, 20, 0.86)",
    zIndex: 10,
  },
  gateOverlayText: {
    color: "#f7c35f",
    fontSize: 22,
    fontWeight: "900",
    marginTop: 18,
  },
  gateOverlaySub: {
    color: "#cbd5e1",
    fontSize: 13,
    marginTop: 6,
  },
});
