import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: {
    minHeight: "100%",
    backgroundColor: "#111827",
  },
  centered: {
    minHeight: "100%",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  bootText: {
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "700",
  },
  authLayout: {
    minHeight: 720,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 42,
    padding: 32,
  },
  authArt: {
    width: "48%",
    minWidth: 360,
    maxWidth: 620,
    height: 470,
    justifyContent: "flex-end",
    overflow: "hidden",
    borderRadius: 8,
    backgroundColor: "#1d3557",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
  },
  sun: {
    position: "absolute",
    top: 60,
    right: 86,
    width: 86,
    height: 86,
    borderRadius: 43,
    backgroundColor: "#f7c35f",
  },
  colosseum: {
    height: 270,
    marginHorizontal: 32,
    marginBottom: 34,
    borderTopLeftRadius: 180,
    borderTopRightRadius: 180,
    backgroundColor: "#d7a35d",
    borderWidth: 8,
    borderColor: "#f2d493",
    alignItems: "center",
    justifyContent: "flex-end",
  },
  archRow: {
    position: "absolute",
    top: 104,
    left: 28,
    right: 28,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  arch: {
    width: 54,
    height: 92,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: "#6f4f38",
  },
  gate: {
    width: 116,
    height: 132,
    borderTopLeftRadius: 58,
    borderTopRightRadius: 58,
    backgroundColor: "#263140",
    borderWidth: 6,
    borderColor: "#593e2c",
  },
  authPanel: {
    width: "42%",
    minWidth: 330,
    maxWidth: 480,
    padding: 28,
    borderRadius: 8,
    backgroundColor: "#f8fafc",
    gap: 14,
  },
  kicker: {
    color: "#b7791f",
    fontSize: 13,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  title: {
    color: "#111827",
    fontSize: 42,
    fontWeight: "900",
    lineHeight: 48,
  },
  subtitle: {
    color: "#4b5563",
    fontSize: 16,
    lineHeight: 23,
  },
  modeRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 6,
  },
  modeButton: {
    flex: 1,
    alignItems: "center",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    paddingVertical: 11,
    backgroundColor: "#ffffff",
  },
  modeButtonActive: {
    backgroundColor: "#111827",
    borderColor: "#111827",
  },
  modeButtonText: {
    color: "#475569",
    fontSize: 14,
    fontWeight: "800",
  },
  modeButtonTextActive: {
    color: "#f8fafc",
  },
  input: {
    height: 48,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#ffffff",
    color: "#111827",
    fontSize: 16,
    paddingHorizontal: 14,
  },
  errorText: {
    color: "#b91c1c",
    fontSize: 14,
    lineHeight: 20,
  },
  primaryButton: {
    minHeight: 50,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
    backgroundColor: "#d97706",
    paddingHorizontal: 18,
  },
  primaryButtonText: {
    color: "#fff7ed",
    fontSize: 16,
    fontWeight: "900",
  },
  buttonPressed: {
    transform: [{ translateY: 1 }],
    opacity: 0.9,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
});
